services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    command: >
      sh -c "
      ./app/wait-for-it.sh db:5432 --timeout=30 --strict &&
      ./app/wait-for-it.sh minio:9000 --timeout=30 --strict &&
      uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
      "
    depends_on:
      - db
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:5000/health"]
      interval: 10s
      timeout: 15s
      retries: 5

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: minio_store
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3

  minio_setup:
    container_name: minio_setup
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set myminio http://minio:9000 minioadmin minioadmin &&
      mc mb -p myminio/audio-files || true &&
      mc anonymous set public myminio/audio-files
      "
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      app:
        condition: service_healthy
    command: >
      sh -c "
      ./wait-for-it.sh app:5000 --timeout=30 --strict &&
      npm start
      "

volumes:
  postgres_data:
  minio_data:
